#使用前★必注意
#请将范例中的【全部】设置【均】复制粘贴
#值为【False】的键或值未被使用的键【不可】不复制
#exampleRecipe:
  #Name: "&f生物书（1星）"
  #UseShardName: "&f碎片"
  #UseShardAmount: 11
  #WinProbability: 19#Note that this must be an integer
  #WinItemName: "&f生物书（2星）"
  #WinItemLore:
  #- "&f这是一个德宝"
  #- "&f这是一个一个德宝"
PlaceholderSlots:
  - 0
  - 1
  - 2
  - 4
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 20
  - 21
  - 22
  - 23
  - 24
  - 26
  - 27
  - 28
  - 29
  - 30
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
exampleRecipe:
  Name: "&f生物书（1星）"
  UseShard: False
  UseShardName: "&f碎片"
  UseShardAmount: 1
  WinProbability: 19
  WinItemName: "&f生物书（2星）"
  WinItemLore:
  - "&f这是一个德宝"
  - "&f这是一个一个德宝"

